### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-metadata-editor#71]
This is failing to build on staging. Full details at https://travis-ci.org/openaq/openaq-metadata-editor/builds/588472566#L252

```
Javascript error: { Error: Cannot find module '../components/map-edit' from '/home/travis/build/openaq/openaq-metadata-editor/app/assets/scripts/views'

    at /home/travis/build/openaq/openaq-metadata-editor/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21

    at load (/home/travis/build/openaq/openaq-metadata-editor/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)

    at onex (/home/travis/build/openaq/openaq-metadata-editor/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)

    at /home/travis/build/openaq/openaq-metadata-editor/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47

    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Comment by olafveerman** [comment]
cc @necoline @sethvincent

**Comment by necoline** [comment]
We deleted the map-edit component [here](https://github.com/openaq/openaq-metadata-editor/pull/66). It looks like I missed a step somewhere.
